use axum::{
    body::{Body, Bytes, HttpBody},
    http::{Request, Response, StatusCode, header},
    response::IntoResponse,
};
use futures::Future;
use std::{
    convert::Infallible,
    pin::Pin,
    task::{Context, Poll},
};
use tower::Service;
use tower_http::services::ServeFile;

/// A service that validates a given request before serving the underneath `ServeFile`.
///
/// This service takes a validator function that returns `Result<Option<Response>, StatusCode>`, which
/// determines what kind of response will be generated.
///
/// `Ok(Some(response))`
///     The response generated by the validator will be used as-is.
///
/// `Ok(None)`
///     The underlying `ServeFile` will provide the response.
///
/// `Err(status)`
///     The underlying `ServeFile` will provide the response, with the appropriate status code set.
#[derive(Clone, Debug)]
pub struct ConditionalServeFile<F> {
    validator: F,
    serve_file: ServeFile,
}

impl<F> ConditionalServeFile<F> {
    pub fn new(validator: F, serve_file: ServeFile) -> Self {
        ConditionalServeFile {
            validator,
            serve_file,
        }
    }
}

impl<F, Fut> Service<Request<Body>> for ConditionalServeFile<F>
where
    F: Fn(Request<Body>) -> Fut + Clone + Send + 'static,
    Fut: Future<Output = Result<Option<axum::response::Response>, StatusCode>> + Send + 'static,
    Body: Send + 'static,
{
    type Response = Response<Body>;
    type Error = Infallible;
    type Future = Pin<Box<dyn Future<Output = Result<Self::Response, Self::Error>> + Send + 'static>>;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        <ServeFile as Service<axum::http::Request<Body>>>::poll_ready(&mut self.serve_file, cx)
    }

    fn call(&mut self, req: Request<Body>) -> Self::Future {
        let validator = self.validator.clone();
        let mut serve_file = self.serve_file.clone();
        Box::pin(async move {
            Ok(match validator(req).await {
                Ok(Some(res)) => res.into_response(),
                Ok(None) => {
                    let req = Request::builder()
                        .uri("/")
                        .body(Body::empty())
                        .expect("valid arguments should have created this request");
                    let res = <ServeFile as Service<axum::http::Request<Body>>>::call(
                        &mut serve_file,
                        req,
                    )
                    .await
                    .into_response();
                    res
                }
                Err(status) => {
                    let req = Request::builder()
                        .uri("/")
                        .body(Body::empty())
                        .expect("valid arguments should have created this request");
                    let mut res = <ServeFile as Service<axum::http::Request<Body>>>::call(
                        &mut serve_file,
                        req,
                    )
                    .await
                    .into_response();
                    *res.status_mut() = status;
                    res
                }
            })
        })
    }
}
