[package]
name = "test-pmr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.50"
git2 = "0.13"
gix = "^0.48"
mockall = "0.10.2"
pmrcore = "0.1.0"
pmrctrl = { version = "0.1.0", optional = true }
pmrmodel = { version = "0.1.0", optional = true }
pmrrepo = { version = "0.1.0", optional = true }
tempfile = "3.1.0"
textwrap-macros = "0.3.0"

[dev-dependencies]
async-std = "1.5.0"

[features]
model = ["dep:pmrmodel"]
repo = ["dep:pmrrepo"]
platform = ["model", "repo", "dep:pmrctrl"]
