[package]
name = "pmrtqs"
version = "0.1.0"
authors = ["Tommy Yu <tommy.yu@auckland.ac.nz>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-recursion = "1.0.0"
clap = { version = "4.2", features = [ "derive", "env" ] }
dotenvy = "0.15.0"
futures = "0.3"
log = { version = "0.4", features = ["std", "serde"] }
pmrcore = { version = "0.1", features = ["sqlx", "display"] }
pmrmodel = "0.1.0"
pmrrepo = "0.1.0"
serde = "1.0.59"
serde_json = "1.0.59"
sqlx = { version = "0.7.0", features = ["sqlite"] }
stderrlog = "0.5.1"

[dev-dependencies]
async-std = { version = "1.5.0", features = [ "attributes" ] }
async-trait = "0.1.50"
mockall = "0.10.2"
tempfile = "3.1.0"
textwrap-macros = "0.3.0"
